source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'salon-online' do
    pod 'AFNetworking', '~> 3.0'
    pod 'AWSS3'
    pod 'Firebase/Core', '= 4.5.0'
    pod 'FSCalendar'
end
